namespace Stationeers.Compiler
{
    public enum TokenType
    {
        Comment,
        Keyword,
        Identifier,
        Number,
        String,
        Constant,

        Symbol_LeftParentheses,
        Symbol_RightParentheses,
        Symbol_LeftBrace,
        Symbol_RightBrace,
        Symbol_LeftBracket,
        Symbol_RightBracket,
        Symbol_Comma,
        Symbol_Dot,
        Symbol_Semicolon,
        Symbol_Equal,
        Symbol_EqualEqual,
        Symbol_NotEqual,
        Symbol_LessThen,
        Symbol_LessThenOrEqual,
        Symbol_GreaterThen,
        Symbol_GreaterThenOrEqual,
        Symbol_Plus,
        Symbol_Minus,
        Symbol_Asterik,
        Symbol_Slash,
        Symbol_And,
        Symbol_Pipe,
        Symbol_Tilde,
        Symbol_Hat,
        Symbol_LogicalNot,
        Symbol_LogicalOr,
        Symbol_LogicalAnd
    }
}
